### ISSUE TITLE
Template on entity

### ISSUE THREAD

**Issue by Chreece** [vasqued2/ha-teamtracker#116]
Thank you very much for this beautiful card, wonderful work done.
I just wanted to pass dynamically the entity so I can always have the next game of my favourite time shown, since there are different entities for different competitions, for the same team.
Is there any chance to accept templates on the entity?

**Comment by Chreece** [comment]
Sorry this is a feature request for the card

**Comment by vasqued2** [comment]
Look into using the Conditional Card or Auto Entities Card to display just the sensors you want to display.  The Wiki provides the basics but you should be able to use whatever conditions you want instead of the sensor state.

[https://github.com/vasqued2/ha-teamtracker/wiki/Using-Conditional-Cards-to-Hide-NOT_FOUND-Status](https://github.com/vasqued2/ha-teamtracker/wiki/Using-Conditional-Cards-to-Hide-NOT_FOUND-Status)

[https://github.com/vasqued2/ha-teamtracker/wiki/Using-Auto-Entities-Card-to-Hide-NOT_FOUND-Status](https://github.com/vasqued2/ha-teamtracker/wiki/Using-Auto-Entities-Card-to-Hide-NOT_FOUND-Status)
