### ISSUE TITLE
Tennis?

### ISSUE THREAD

**Issue by mschut** [vasqued2/ha-teamtracker#125]
First of all: probably very sorry. However, I just cant get the tennis info working. I have tried, but keep on getting "not found". Already changed my language setting to english, although I think that is an old issue (I have read the other tennis issue). 

Can someone please post an example of exactly what info to put into the boxes for adding a tennis player? I am trying the name, the id, just the surname. Always resulting in "not found".

**Comment by vasqued2** [comment]
If you are on v0.10.0 for both the sensor and the card, my guess is that you have it set up correctly and the API isn't returning much info due to the holidays.  The only tournament returned for ATP is Next Gen ATP Finals presented by NEOM which looks like it was a smaller tournament at the end of November.  For WTA it's only returning info for Open BLS de Limoges.

Below is the YAML config that works for me to track Medjedovic.  If this doesn't for you, let me know and we can dig in further.  I am currently working on a language override that won't force you to set the full language to English.  I may have you try a pre-release version of that if you still have problems. 

```
  - platform: teamtracker
    league_id: ATP
    team_id: Medjedovic
    name: test_tt_all_teste01
```

**Comment by mschut** [comment]
You are right! I do get info with Medjedovic. So it is working, will be patient and try again in a few weeks. Thanks!

**Comment by vasqued2** [comment]
Glad to hear it's working for you.  I finally got the language override working if it's ever needed.

If you upgrade to v0.11.0 for both the sensor and the card, you can use the new `api_language `configuration option to override your local language an use whatever you want (i.e. `en`). If you set up the sensor via the UI, you can set it via the Configuration option UI for the sensor.
