### ISSUE TITLE
Picture for Bundesliga

### ISSUE THREAD

**Issue by fibbep** [vasqued2/ha-teamtracker#171]
It seems to be an error with the picture/ logos of the Bundesliga soccer clubs in cards. 
![IMG_0271](https://github.com/user-attachments/assets/9012a879-0c01-4d06-ade1-ccf784ef2e13)

**Comment by vasqued2** [comment]
How do you have your sensor set up?  The API is only return the B04 @ BMG game on 8/23 for me and it is displaying correctly.

![image](https://github.com/user-attachments/assets/2402e564-8117-4948-a6cb-6045a1567024)

**Comment by ChipChildress** [comment]
I have the same issue.  ![image](https://github.com/user-attachments/assets/79c29990-ec75-41c9-b2de-1c8c19dded07)

**Comment by vasqued2** [comment]
Appears to be related to the new 8.0 release and the Apple app.  That’s where I will start digging.  If someone is seeing the problem elsewhere, lmk.

**Comment by vasqued2** [comment]
This is definitely the issue introduced in HA 2024.8.0 impacting some other custom cards in the Apple app as well.  Waiting for direction from the HA team on if I need to make a change or if they will fix it on their side in an upcoming release.

**Comment by ChipChildress** [comment]
Thank you. I believe you are correct that it is the IpadOS app. This same page looks fine on my iPhone iOS app.

**Comment by fhuserjr** [comment]
> It seems to be an error with the picture/ logos of the Bundesliga soccer clubs in cards. 
> 
> ![IMG_0271](https://github.com/user-attachments/assets/9012a879-0c01-4d06-ade1-ccf784ef2e13)
> 
> 

same

**Comment by vasqued2** [comment]
This is not team or league related.  

This broke in HA 2024.8,0 for specific devices.  The most common devices impacted are iPads, but experiments with changing the user-agent in Chrome to other devices indicates it could impact others, although I don't have them to confirm.  It impacts other cards besides Team Tracker and has been reported to the HA dev team.  It was not fixed in the 2024.8.1 release.

It always impacts the first Team Tracker card on a refreshed dashboard tab.  It also impacts all other cards on that that or other tabs _with the same state_.  Cards with a state different than the first card render correctly.

This leads to a bizarre workaround that isn't pretty but it works.  If the first Team Tracker card on a tab generates an error, all the regular cards will work.

The easiest way to do this is to create a new Team Tracker card on a tab but do not specify an entity.  Place this card first on your tab.  This will create an error card and all the other card types should display correctly.

Please post device and version information when reporting this problem, otherwise I will assume it is all related and not research your specific issue.

At this point, I am waiting on information from the HA dev team.

Further updates will be made in the card repo.

https://github.com/vasqued2/ha-teamtracker-card/issues/95

**Comment by vasqued2** [comment]
Step by step instructions on the workaround has been posted on the issue on the card repo:  https://github.com/vasqued2/ha-teamtracker-card/issues/95

Please post any comments on that thread going forward.

**Comment by vasqued2** [comment]
I have released v0.14.2-beta1 to address this issue.

Please see discussion thread https://github.com/vasqued2/ha-teamtracker-card/discussions/97 for details and log any issues in that discussion thread or the open issue in the card repo.

**Comment by vasqued2** [comment]
This should be fixed in v0.14.2

**Comment by fhuserjr** [comment]
thank you! looks great
