### ISSUE TITLE
Not Found for Tennessee football. 

### ISSUE THREAD

**Issue by JohnnyCarcinogen** [vasqued2/ha-teamtracker#180]
My sensor for UT football has been showing not found all week. I've got it configured with NCAAF and TENN for the team code. All my other sensors are working fine.

**Comment by vasqued2** [comment]
What `team_id` and `conference_id` are you using?  `team_id` should be `TENN`.  `conference_id` should be `8`.

**Comment by vasqued2** [comment]
Strange.  It worked for me when I tried a couple hours before kickoff.

Did you specify the conference id?  If not, it’s possible that the API hit the limit on number of games returned and because it was  a late game it got truncated until the early games dropped off.

I’ve seen it happen with MLB games before to its at least possible something similar happened to you.

That’s not what happened if you specified a conference id though because there aren’t enough teams in the SEC alone to hit the limit.

**Comment by JohnnyCarcinogen** [comment]
That’s exactly what it was. When I recreated the sensor I neglected the conference ID. Thanks!!
