### ISSUE TITLE
No NFL NE or NYJ

### ISSUE THREAD

**Issue by ddean6232** [vasqued2/ha-teamtracker#182]
Integration shows "not found" for NE and NYJ.  I have 8 other integrations working great.  Is it the API or do I have the wrong codes?  I have tried NEW, NEP, NEWP, NENG... Nothing...

**Comment by vasqued2** [comment]
The codes are NE and NYJ.

Wait another day or two.  The API doesn't start returning next Sunday's games until Tuesday (or maybe Wed, I can't remember).  But since they played last Thursday instead of Sunday, their past game is too far back to be returned too so you get `NOT_FOUND` until it starts returning next Sunday's games.

**Comment by vasqued2** [comment]
As expected NE is working as of Tuesday once the next weeks games were returned by the API

**Comment by ddean6232** [comment]
Thanks David... Got it now.  I did read the wiki and found the Not Found
section. Sorry for the trouble.
