### ISSUE TITLE
English Championship please

### ISSUE THREAD

**Issue by coleburg** [vasqued2/ha-teamtracker#19]
Not an issue but a request for the English Championship league to be added please.

**Comment by coleburg** [comment]
Hi, the English Championship is the league below the Premier league, here is a link

https://www.espn.co.uk/football/scoreboard/_/league/eng.2 or
https://www.espn.com/soccer/league/_/name/eng.2

thank you

**Comment by vasqued2** [comment]
It’s already supported.

You have to set up the sensor to use a custom API configuration instead of a native API configuration.  [Here’s a link with details. ](https://github.com/vasqued2/ha-teamtracker/wiki/Custom-API-Configurations) There are far too many soccer leagues to support them all natively.

Use `eng.2` as the `league_path`

You’ll end up with something like this:
```
# Custom Integration - 
  - platform: teamtracker
    league_id: XXX
    team_id: SUN
    sport_path: soccer
    league_path:  eng.2
    name: team_tracker
```

**Comment by vasqued2** [comment]
Glad to hear it.
