### ISSUE TITLE
UFC main card

### ISSUE THREAD

**Issue by blockloop** [vasqued2/ha-teamtracker#193]
UFC events are labeled by the main card. For example `UFC 309: Jones vs. Miocic`. When using this plugin with the ha-teamtracker-card it shows me the first early prelim fight, which most people don't even watch. I started to write this issue on the frontend card, but realized the sensor data is where the data comes  from.

I don't know if this is a feature or the way it should work. Is there any way to show the main card until the event starts?

![image](https://github.com/user-attachments/assets/bf8e9ec5-4ad5-4f3c-8453-298704a0961a)
![image](https://github.com/user-attachments/assets/407c2eb0-04ab-45e9-b50f-9ef6244e689b)
![image](https://github.com/user-attachments/assets/3b88e6d4-cd05-4ca6-a41f-b11ea53953c2)

**Comment by vasqued2** [comment]
Using `*` as the `team_id` will bring up the next upcoming fight, which is the first fight on the undercard.  You could use `miocic` for the `team_id` and it would match on the main event and show those fighters, but in that case it would only return the main event and none of the undercard fights.  And you would have to change the card for each new event so that is a pain.

The `event_id` displayed at the top of the card is being set the the event shortName (UFC 309).  It looks like there is an alternate full name (UFC 309: Jones vs. Miocic) that could be returned instead.  The fighters for the first undercard would still be shown because they are the next upcoming fight, but the event name would show `UFC 309: Jones vs. Miocic`.  Thoughts?

**Comment by vasqued2** [comment]
v0.14.5 will return the long name instead of the short event name.  The first undercard fight will still be displayed but the title will reflect the main event.

![image](https://github.com/user-attachments/assets/12351712-3464-4188-b07c-019d267eb2ae)

**Comment by blockloop** [comment]
Beautiful, thank you
