### ISSUE TITLE
Invalid message when there's an upcoming game

### ISSUE THREAD

**Issue by ThatTallGuy21** [vasqued2/ha-teamtracker#196]
Noticed this happens sometimes where there is an upcoming game but the team tracker card doesn't pick it up. It'll either show an incorrect date in the card or it'll show a message like the season is over.

![Screenshot_20241211-082540](https://github.com/user-attachments/assets/4810ae95-94a3-4194-a76b-24058aff0265)

**Comment by vasqued2** [comment]
The ESPN API is not returning any B10 games at this time and so it uses the default date.  This is normal for the dead period between the conference championship and the playoffs.  Just wait a couple days and it should populate.  I'll keep an eye on it and will make a fix if there are still problems once it populates.

I realize that this may be a new experience for teams that don't normally make the playoffs because they can't beat Ohio State,  but this happens every year.  :-)

**Comment by vasqued2** [comment]
Confirmed working as of today.
