### ISSUE TITLE
World Cup - Entities Unavailable

### ISSUE THREAD

**Issue by jesushairdo** [vasqued2/ha-teamtracker#24]
Whenever I create an entity for a World Cup team, the status shows as Unavailable with an entry in the error logs of `Error fetching Team-Tracker-ENG-World-Cup data: 'venue'`.

I have created entities for 2 different teams and get the same errors for each team:

```
Entity 1
League: WC
Team/Athlete: ENG
Friendly Name: Team-Tracker-ENG-World-Cup
Update Timeout: 120

Entity 2
League: WC
Team/Athlete: USA
Friendly Name: Team-Tracker-USA-World-Cup
Update Timeout: 120
```

I'm pretty sure that the team name is correct as if I enter a nonsense name (e.g. XXX) the entity is added with a 'NOT_FOUND' status and no errors in the log files

**Comment by vasqued2** [comment]
Is it working now?  USA is working for me right now.  My guess is that the API wasn't initially returning venue data but now it is but I don't have the history on my machine to know for sure.

I reviewed the code and it assumes venue data is always provided by the API.  I can make a quick change to make it optional, but I'd like one of you to confirm it's working now.  If it still isn't working for you now, then the problem is something else and I'll need to get more info from your debug logs.

**Comment by cburbs** [comment]
It is working now ...thanks

**Comment by jesushairdo** [comment]
I can confirm it's working for me too. Thanks for checking :)

**Comment by vasqued2** [comment]
Thanks for confirming.  I’ll push a change so it will still work if the API ever is missing the venue info in the future.  Thanks for the error log info, otherwise this would have been near impossible to track down

**Comment by vasqued2** [comment]
v0.5.2 has a quick fix so if it ever happens again, the sensor will handle it gracefully instead of erroring out.
