### ISSUE TITLE
NOT_FOUND: Behavior is different from ha-nfl

### ISSUE THREAD

**Issue by bgulla** [vasqued2/ha-teamtracker#49]
RIght now, I am trying to add NFL: Baltimore Ravens (BAL). I am receiving `NOT_FOUND` because the ravens are not scheduled to play between now and Dec 31st. If I add the same team to `ha-nfl` it adds the team correctly with `POST` (since the team played Saturday)

I would expect the behavior not to return `NOT_FOUND`, why even add the date to restrict the availability of adding a team?

**Comment by vasqued2** [comment]
Where I'm from, not displaying Ravens games is considered a feature, not a bug.  🤣 

Seriously though, the ha-nfl has the luxury of only having to deal with NFL schedules.  ha-nfl looks at the entire NFL week that starts on Tuesday and runs through the next Monday.  Thus it will show the upcoming Monday night games earlier and the retain all completed games until the new week is loaded sometime on Tuesday.

Because team_tracker supports multiple sports, I don't have that luxury.  I initially did not date-bound the API and used the API defaults.  When I did this, the NFL worked the same as ha-nfl, but many other sports that are not on a weekly cadence (basketball, soccer, baseball  college sports, etc.) often did not return games by default until a day or two before they were scheduled or returned multiple games (i.e. baseball double headers).  This created a ton of confusion because people assumed they set up something wrong instead of realizing they needed to wait until much closer to the game day for the info to appear and I spent a ton of time tracing down "defects" that weren't.  This confusion was magnified because the API looks ahead a different number of days for different sports, and so a game on date X could be returned for one sport but not for another.  Then consider that some soccer teams can play in multiple "leagues" and your head can explode.

By forcing a date range, everything is much more predictable, every sport looks forward and back the same number of days, and many sports that used to get a PRE card only a day or two before the event now get one almost a week early.  In the end I made a design decision that benefits the vast majority of the sports at what I consider a slight inconvenience to the NFL.  And, if you haven't noticed, this also means the API doesn't return BYE data when there is a NFL BYE week either.  I have a strong bias against sport-specific logic and only incorporate it into a few very controlled places when parsing the API response.  There's no way I can support this many sports otherwise.

Selfishly, this change cut down on the number of false "defects" by about 5x-10x and if anyone really wants the NFL calendar, they can use ha-nfl, as you pointed out.  There's no downside to using it and zacs purposely stayed focused on the NFL because he knew there would have to be compromises like this when adding more sports.

Hope this helps you understand my thinking.

And if you ever run into a Modell, kick them in the shin for me.

**Comment by bgulla** [comment]
First off, thanks for the thorough explanation here. I respect the weariness for per sport logic, especially when you are supporting as many sports as you are here. 

Secondly, Art Modell is no friend of mine. If anyone can sympathize with `ripping a team out of a city, it's us. If I am picking up that you're a browns fan... screw API logic, you need to be fighting front office logic.

Thanks for the great work here, at least we're not steelers fans. 🤝
