### ISSUE TITLE
XXX: eng.fa?

### ISSUE THREAD

**Issue by janfajessen** [vasqued2/ha-teamtracker#57]
Today Manchester City plays the FA Cup. I wrote XXX, MNC, soccer and eng.fa.  Like the path on the espn page.  I get the competition with the logo and that there are no upcoming matches, NOT FOUND.  I don't know if it's an API problem.  Although that does not mean that I love this integration and you have done a magnificent job!

**Comment by vasqued2** [comment]
It looks like you have everything set up correctly and I have been able to reproduce the problem based on the info you provided.

It looks like the issue is that the API only returns a max of 25 matches and there are/were 31 matches scheduled for the FA Cup between Jan 7 and Jan 8.  Unfortunately, MNC is one of the 6 that was truncated by the API.  I don't know anything about the FA Cup so it would be good for you to confirm that this is correct.

I never ran into this problem before because no league has ever had more than 25 matches in a single week.  Is this going to be typical or will the numbers drop over time as teams lose?

If this is really the problem, I need to think about how to solve it.  Unfortunately there isn't much you can do w/o an update to the sensor.  I expect you will see the MNC results tomorrow as the games from Jan 7 will drop and only the Jan 8 games will be returned and there are less than 25 of them so the API won't truncate the games.  Going forward, will there be more cases where they will be more than 25 games in a week?

**Comment by janfajessen** [comment]
Yes, there will be another next time that the same teams play but in the opposite field.  Then half will remain in a double game and so on.  Half, half to the final.  It was to know if I had done something wrong, if there is no solution there is no problem.  Surely later with less teams it will work well, in case City qualify he he he.  Thanks

**Comment by vasqued2** [comment]
It will work well when there are less teams.

Reopening until I decide how to handle in the future.

**Comment by janfajessen** [comment]
Ok, I was wrong because I don't know very well how the FA Cup works either because I'm not from there.  It seems that those who have tied play another game and those who have won play the next tie. So yes, the next date will be the ones that have tied and the next one will be half of what there were..
