### ISSUE TITLE
Email ?

### ISSUE THREAD

**Issue by schumi2309** [vasqued2/ha-teamtracker#70]
Good morning,
Have you received my email for the corrections in French?

**Comment by vasqued2** [comment]
I don't monitor that email address on a regular basis so thanks for bringing it up here.

To answer your questions.

1. The information from the scrollbar is displayed as it is provided (and translated) by the ESPN API.  There is no translation file for it.  I simply pass in the requested language (in your case French) and display whatever the API returns.  Based on your comments, it sounds like it returns English even when French is requested.  There is nothing I can do about that.
2. Per your comment that F1 races display a message "No upcoming matches..." instead of "No upcoming races...", the "No upcoming..." message is the same for all sports.  It is not sport specific.  It probably should be something like "No upcoming competitions..." now that it supports such a wide variety of sports.  If you would like to give me a more general translation for "No upcoming..." I'd be glad to make the change in the French translation file.

Also, you may want to take a look at [https://github.com/marcokreeft87/formulaone-card](https://github.com/marcokreeft87/formulaone-card) if you haven't already.  It is an F1-specific card that uses F1-specific APIs to collect a lot more data than is available from the ESPN API.  Because it is dedicated only to F1, the dev has added a lot of F1-specific options that aren't even possible using the ESPN API.  He's been making a lot of enhancements in prep for the upcoming season and you might want to check it out.
