### ISSUE TITLE
Football home and away matches notify in sensor and lovelace card

### ISSUE THREAD

**Issue by copetogo** [vasqued2/ha-teamtracker#99]
First of all great work .I am not sure if it is possible or not in the API but at-least in league football there is a home team and away team and whichever team is playing at home ,that team name comes first. So for example chelsea vs manchester united , chelsea is playing at home , manchester united  away , obviously one case where it is a final being played at neutral venue like a champions league final this won't hold true which we can ignore .

**Comment by vasqued2** [comment]
Different sports/countries have different conventions for which team to display on which side so I made it configurable.

You can force the home team to display on either the left or right side of the card on a per card basis.  Just include _one_ of the following in your card configuration.  Even when teams play at a neutral site, one team is always designated as a home team.

```
home_side: left
home_side: right
```

**Comment by copetogo** [comment]
> Different sports/countries have different conventions for which team to display on which side so I made it user configurable.
> 
> You can force the home team to display on either the left or right side of the card on a per card basis. Just include _one_ of the following in your card configuration. Even when teams play at a neutral site, one team is always designated as a home team.
> 
> ```
> home_side: left
> home_side: right
> ```

You are correct but for football (soccer) this convention is followed everywhere irrespective of the country .when you say home_side is that an exposed attribute in the sensor because i want to use it in the automation.

**Comment by vasqued2** [comment]
MLS has historically been inconsistent based on broadcaster.  If you search enough highlights on Youtube you can see the differences across ESPN, Fox, and local broadcasts and how they've changed over time.  Now that Apple has the games, it appears they are consistently going home team on left.  In any event, it's easy to configure the card to display the home team wherever you want.

There is no left or right side on the sensor so I am a little confused by what you are talking about.  You should use the `team_homeaway` and `opponent_homeaway` attribute on the sensor to determine which team is which, but this doesn't change based on the card configuration or which team the sensor is set up for.  

If it has the wrong values, it's because the API is providing the wrong values.

**Comment by copetogo** [comment]
> MLS has historically been inconsistent based on broadcaster. If you search enough highlights on Youtube you can see the differences across ESPN, Fox, and local broadcasts and how they've changed over time. Now that Apple has the games, it appears they are consistently going home team on left. In any event, it's easy to configure the card to display the home team wherever you want.
> 
> There is no left or right side on the sensor so I am a little confused by what you are talking about. You should use the `team_homeaway` and `opponent_homeaway` attribute on the sensor to determine which team is which, but this doesn't change based on the card configuration or which team the sensor is set up for.
> 
> If it has the wrong values, it's because the API is providing the wrong values.

gotcha .thanks a ton mate got the attribute you mentioned. One last thing although it is not relevant in this thread. For finding team ids how do i go about it .For Eg say F1, i try for verstappen the espn does not show anything, similarly say for football i go on team page of chelsea but in the URL they don't contain the team id  attaching the link for reference https://www.espn.in/football/team/_/id/363/chelsea, i just did a hit and trial for finding team ID. i know i am doing something pretty stupid.

**Comment by vasqued2** [comment]
verstappen should work for f1.  The API is showing this week's Qatar Airways Emilia Romagna Grand Prix is cancelled and so that's why is isn't returning any results.  It usually populates the drivers a day or two before the first time trial so wait until you get closer the next race.  You are probably OK.

Chelsie is CHE.  Or at least it is in the US.  This is the short team abbreviation you see on the left side of the page you linked to with the schedule.  Note that this can change based on your language and can get really confusing if you have HA using one language and your browser using another.

I can't remember the details but I think Manchester United is abbreviated MAN in the US but MUN in other countries.  In the worst case scenario, you can always turn on the debug mode and check the logs to get the actual API that is being used, call it directly, and look at the json to see what is being used.

**Comment by copetogo** [comment]
> verstappen should work for f1. The API is showing this week's Qatar Airways Emilia Romagna Grand Prix is cancelled and so that's why is isn't returning any results. It usually populates the drivers a day or two before the first time trial so wait until you get closer the next race. You are probably OK.
> 
> Chelsie is CHE. Or at least it is in the US. This is the short team abbreviation you see on the left side of the page you linked to with the schedule. Note that this can change based on your language and can get really confusing if you have HA using one language and your browser using another.
> 
> I can't remember the details but I think Manchester United is abbreviated MAN in the US but MUN in other countries. In the worst case scenario, you can always turn on the debug mode and check the logs to get the actual API that is being used, call it directly, and look at the json to see what is being used.

Thanks so much for your prompt reply. It shows the code owner is interested in maintaining this integration (have had a poor experience before). a suggestion on my part would be is not everyone is versed with viewing json files. May be sample example  like you have done for so many steps for finding team code will be nice specifically for the case when team code is not viewable in the URL Closing the issue :)
